household <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?", colClasses = c('character', 'character', 'numeric',  'numeric', 'numeric', 'numeric', 'numeric', 'numeric', 'numeric'))
household <- na.omit(household)
housedata <- household[household$Date %in% c("1/2/2007", "2/2/2007"),]
housedata$Date <- strptime(paste(housedata$Date,housedata$Time), "%d/%m/%Y %H:%M:%S")
# make a png file and put the content in
png(filename = "Plot4.png", width = 480, height = 480, units = "px", pointsize = 12)
par(mfrow = c(2,2), mar = c (4, 4, 2, 1), oma = c(2, 2, 2, 2))
plot(housedata$Date, housedata$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power(kilowatts)")
plot(housedata$Date, housedata$Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
plot(housedata$Date, housedata$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
  lines(housedata$Date, housedata$Sub_metering_2, type = "l", col = "red")
  lines(housedata$Date, housedata$Sub_metering_3, type = "l", col = "blue")
  legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lwd = 0.75)
plot(housedata$Date, housedata$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power")
dev.off()